export const ALL_ARTICLES = 'ALL_ARTICLES';
export const ADD_ARTICLE = 'ADD_ARTICLE';
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
export const PUBLISH_ARTICLE = 'PUBLISH_ARTICLE';
